env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/order:
    - error
    -
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
        - unknown
      newlines-between: always
      warnOnUnassignedImports: true
      alphabetize:
        order: asc
        caseInsensitive: false
